services:
  spark-job:
    build: .
    image: spark-realtime-custom
    container_name: spark-streaming-job
    ports:
      - "4040:4040"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - INPUT_DATA_DIR=./data/input
      - EVENTS_PER_SECOND=${EVENTS_PER_SECOND:-2.0}
      - BATCH_PROCESSING_TIME=${BATCH_PROCESSING_TIME:-5}
    volumes:
      - ./:/home/jovyan/work
    working_dir: /home/jovyan/work
    networks:
      - spark-net
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      spark-submit  --packages org.postgresql:postgresql:42.7.2  src/spark_streaming_to_postgres.py

  data-generator:
    build: .
    image: spark-realtime-custom
    container_name: data-generator
    environment:
      - INPUT_DATA_DIR=./data/input
      - EVENTS_PER_SECOND=${EVENTS_PER_SECOND:-2.0}
    volumes:
      - ./:/home/jovyan/work
    working_dir: /home/jovyan/work
    networks:
      - spark-net
    command: python src/data_generator.py

  tests:
    build: .
    image: spark-realtime-custom
    container_name: system-tests
    profiles: [ "test" ]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./:/home/jovyan/work
    working_dir: /home/jovyan/work
    networks:
      - spark-net
    depends_on:
      postgres:
        condition: service_healthy
    command: pytest tests/ -v -s

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/postgres_setup.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge

volumes:
  postgres-data:
